# Generated by Django 5.2.3 on 2025-06-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', models.IntegerField(unique=True)),
                ('repo_full_name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField()),
                ('analysis', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
