name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    services:
      redis: redis
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: {python-version: '3.11'}
      - run: pip install -r backend/requirements.txt
      - run: |
          cd backend
          python manage.py migrate
          python manage.py test

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with: {node-version: '18'}
      - run: |
          cd frontend
          yarn install --frozen-lockfile
          yarn build
